version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - local_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    env_file:
      - ../.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin4

volumes:
  local_data:
  pgadmin_data:
